apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: vd9v6748x-java-quarkus
  janus-idp.io/tekton: vd9v6748x-java-quarkus
  backstage.io/kubernetes-id: vd9v6748x-java-quarkus
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: vd9v6748x-java-quarkus
resources:
- deployment.yaml
- route.yaml
- service.yaml
